# build_payload.ps1
# Rebuilds rsg_documents.json and rsg_import.sql from the three reviewed CSVs in
# this folder. Run after editing policies.csv / sops.csv / policy_sop_links.csv.
#
#   pwsh -File build_payload.ps1     (or Windows PowerShell: powershell -File ...)

$ErrorActionPreference = "Stop"
$base = $PSScriptRoot
$RSG_ORG = "a0000000-0000-4000-8000-000000000001"
$enc = New-Object System.Text.UTF8Encoding($false)

function ParseMeta($s) {
  $o = [ordered]@{}
  if ([string]::IsNullOrWhiteSpace($s)) { return $o }
  foreach ($pair in ($s -split ';\s*')) {
    $kv = $pair -split '=', 2
    if ($kv.Count -eq 2 -and $kv[0].Trim() -ne '' -and $kv[1].Trim() -ne '') {
      $o[$kv[0].Trim()] = $kv[1].Trim()
    }
  }
  return $o
}

$policies = @()
foreach ($r in (Import-Csv (Join-Path $base "policies.csv"))) {
  $name = $r.policy_name.Trim()
  $dt = "policy"
  if ($r.document_type)                       { $dt = $r.document_type.Trim() }
  elseif ($r.review -match 'doc_type=([a-z]+)') { $dt = $Matches[1] }
  elseif ($name -match 'HANDBOOK|Handbook')    { $dt = "handbook" }
  elseif ($name -match 'Procedure$')           { $dt = "procedure" }
  elseif ($name -match '^Disaster Plan')       { $dt = "plan" }
  elseif ($name -match 'Agreement$')           { $dt = "agreement" }
  $meta = [ordered]@{}
  if ($r.parent_list_source -and $r.parent_list_source -ne $name) { $meta["parent_list_name"] = $r.parent_list_source }
  if ($r.review) { $meta["import_review"] = $r.review }
  $p = [ordered]@{ name = $name; status = $r.status; is_parent_facing = ($r.is_parent_facing -eq 'true'); document_type = $dt }
  if ($r.program) { $p["program"] = $r.program }
  if ($r.site -and $r.site.Trim() -and $r.site.Trim().ToLower() -ne 'multicampus') { $p["site"] = $r.site.Trim() }
  if ($meta.Count -gt 0) { $p["metadata"] = $meta }
  $policies += $p
}

$sops = @()
foreach ($r in (Import-Csv (Join-Path $base "sops.csv"))) {
  $name = $r.sop_name.Trim()
  $notes = $r.priority_notes
  $priority = $null
  if ($notes -match 'PRIORITY\s+(\d)') { $priority = [int]$Matches[1] }
  $meta = ParseMeta $r.tier_metadata
  if ($r.section_or_area) { $meta["section"] = $r.section_or_area.Trim() }
  $s = [ordered]@{ name = $name; target_tier = $r.tier }
  if ($r.site -and $r.site.Trim() -and $r.site.Trim().ToLower() -ne 'multicampus') { $s["site"] = $r.site.Trim() }
  if ($r.sop_status)   { $s["status"] = $r.sop_status }
  if ($r.signoff_type) { $s["signoff_type"] = $r.signoff_type }
  if ($null -ne $priority) { $s["priority"] = $priority }
  if ($notes)          { $s["notes"] = $notes }
  if ($meta.Count -gt 0) { $s["metadata"] = $meta }
  $sops += $s
}

$links = @()
foreach ($r in (Import-Csv (Join-Path $base "policy_sop_links.csv"))) {
  $links += [ordered]@{ sop_tier = $r.sop_tier; sop_name = $r.sop_name.Trim(); policy_name = $r.policy_name.Trim(); confidence = $r.confidence }
}

$json = ([ordered]@{ policies = $policies; sops = $sops; links = $links } | ConvertTo-Json -Depth 8)
[System.IO.File]::WriteAllText((Join-Path $base "rsg_documents.json"), $json, $enc)

if ($json.Contains('$payload$')) { throw "payload contains the dollar-quote delimiter" }
$nl = "`r`n"; $dq = '$payload$'
$sql = @(
  "-- rsg_import.sql  (generated by build_payload.ps1, do not edit by hand)",
  "-- Calls the generic importer with RSG's reviewed inventory. Idempotent.",
  "-- Prerequisite: migrations 0001-0005 applied and seed/0001_tenants.sql run.",
  "",
  "select public.import_documents(",
  "  '$RSG_ORG'::uuid,",
  "  $dq",
  $json,
  "  ${dq}::jsonb",
  ");",
  ""
) -join $nl
[System.IO.File]::WriteAllText((Join-Path $base "rsg_import.sql"), $sql, $enc)

Write-Host ("policies={0} sops={1} links={2}" -f $policies.Count, $sops.Count, $links.Count)
