-- 0082_contract_signed_copy.sql
--
-- Step 57 Part A: signed PDFs for contracts. Signing today only records a
-- typed name, timestamp and hash - there is no document with the signature
-- on it. This adds the columns for a drawn signature and a generated signed
-- copy (original pages + one execution page), plus two document owner types
-- to hold them.
--
-- Numbered 0082, not the spec's 0074 - migrations 0074-0081 already exist
-- (AI Q&A work, applied to this database, not yet committed to git when this
-- was written).

alter table public.contracts
  add column requires_countersign boolean not null default true,
  add column signed_signature_document_id uuid references public.documents(id) on delete set null,
  add column countersigned_signature_document_id uuid references public.documents(id) on delete set null,
  add column signed_copy_document_id uuid references public.documents(id) on delete set null,
  add column signed_copy_hash text,
  add column signed_copy_generated_at timestamptz;

comment on column public.contracts.requires_countersign is
  'Ticked by default on upload. Unticked for a PDF the employer already signed - executionState() then treats the contract as executed as soon as the employee signs, with no awaiting_countersign state.';

-- Contracts hold pay rates and personal terms and have no reason to be
-- text-extracted (Step 56's pipeline runs on every upload today, including
-- contracts, and writes the result to documents.extracted_text).
update public.documents set extracted_text = null where owner_type = 'contract';

alter table public.documents drop constraint documents_owner_type_check;
alter table public.documents add constraint documents_owner_type_check
  check (owner_type in ('policy', 'sop', 'contract', 'credential', 'identity', 'sop_evidence', 'signature', 'signed_copy'));

-- documents_select (0038): signature and signed_copy get exactly the same
-- visibility as the contract they belong to - both branches already need
-- the identical "owner or HR-manager/admin at service" predicate, so they
-- join the existing contract branch rather than adding a near-duplicate one.
drop policy if exists documents_select on public.documents;
create policy documents_select on public.documents
  for select using (
    public.in_org(organisation_id)
    and (
      owner_type in ('policy', 'sop')
      or (owner_type in ('contract', 'signature', 'signed_copy') and exists (
        select 1 from public.contracts c
        where c.id = documents.owner_id
          and (c.profile_id = (select auth.uid())
               or public.covers_service(c.organisation_id,
                                        public.worker_service(c.profile_id)))
      ))
      or (owner_type = 'identity' and exists (
        select 1 from public.identity_documents d
        where d.id = documents.owner_id
          and (d.profile_id = (select auth.uid())
               or public.can_manage_worker(d.organisation_id,
                                           public.worker_service(d.profile_id)))
      ))
      or (owner_type in ('credential', 'sop_evidence')
          and public.is_manager(organisation_id))
    )
  );

-- documents_write (0044): signature and signed_copy are generated by the
-- act of signing/countersigning itself, so - unlike the 'contract' branch,
-- which migration 0063 deliberately locks out the contract's own owner from
-- (a staff member must never edit their own contract's terms or file) -
-- these two owner types must also allow the contract's own profile_id, since
-- generateContractSignedCopy() runs in the same request, under the same
-- caller-scoped client, as signOwnContract() itself.
drop policy if exists documents_write on public.documents;
create policy documents_write on public.documents
for all
using (
  in_org(organisation_id) and (
    (owner_type in ('policy', 'sop') and can_edit_content(organisation_id))
    or (
      owner_type = 'contract'
      and exists (
        select 1 from public.contracts c
        where c.id = documents.owner_id
          and (
            is_admin(c.organisation_id)
            or (can_verify(c.organisation_id) and worker_service(c.profile_id) = current_service())
          )
      )
    )
    or (
      owner_type in ('signature', 'signed_copy')
      and exists (
        select 1 from public.contracts c
        where c.id = documents.owner_id
          and (
            c.profile_id = (select auth.uid())
            or is_admin(c.organisation_id)
            or (can_verify(c.organisation_id) and worker_service(c.profile_id) = current_service())
          )
      )
    )
    or (
      owner_type = 'identity'
      and exists (
        select 1 from public.identity_documents d
        where d.id = documents.owner_id
          and (
            d.profile_id = (select auth.uid())
            or can_manage_worker(d.organisation_id, worker_service(d.profile_id))
          )
      )
    )
    or (owner_type in ('credential', 'sop_evidence') and is_manager(organisation_id))
  )
)
with check (
  in_org(organisation_id) and (
    (owner_type in ('policy', 'sop') and can_edit_content(organisation_id))
    or (
      owner_type = 'contract'
      and exists (
        select 1 from public.contracts c
        where c.id = documents.owner_id
          and (
            is_admin(c.organisation_id)
            or (can_verify(c.organisation_id) and worker_service(c.profile_id) = current_service())
          )
      )
    )
    or (
      owner_type in ('signature', 'signed_copy')
      and exists (
        select 1 from public.contracts c
        where c.id = documents.owner_id
          and (
            c.profile_id = (select auth.uid())
            or is_admin(c.organisation_id)
            or (can_verify(c.organisation_id) and worker_service(c.profile_id) = current_service())
          )
      )
    )
    or (
      owner_type = 'identity'
      and exists (
        select 1 from public.identity_documents d
        where d.id = documents.owner_id
          and (
            d.profile_id = (select auth.uid())
            or can_manage_worker(d.organisation_id, worker_service(d.profile_id))
          )
      )
    )
    or (owner_type in ('credential', 'sop_evidence') and is_manager(organisation_id))
  )
);

-- sign_own_contract / countersign_contract (0044): add the signature
-- document id parameter. Explicit drops first - "create or replace" with a
-- different argument list creates a second overload rather than replacing
-- the old one, which would leave the pre-fix 3-argument countersign_contract
-- (missing the self-countersign check below) still callable.
drop function if exists public.sign_own_contract(uuid, text, text);
drop function if exists public.countersign_contract(uuid, text, text);

create function public.sign_own_contract(
  p_contract_id uuid,
  p_signed_name text,
  p_signed_content_hash text,
  p_signature_document_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_profile_id uuid;
  v_superseded_at timestamptz;
  v_is_deed boolean;
  v_signed_at timestamptz;
begin
  select profile_id, superseded_at, is_deed, signed_at
    into v_profile_id, v_superseded_at, v_is_deed, v_signed_at
  from public.contracts
  where id = p_contract_id
  for update;

  if v_profile_id is null or v_profile_id <> v_uid then
    raise exception 'Contract not found.';
  end if;
  if v_superseded_at is not null then
    raise exception 'This contract has been replaced.';
  end if;
  if v_is_deed then
    raise exception 'This contract is a deed and is signed on paper, not in the portal.';
  end if;
  if v_signed_at is not null then
    return;
  end if;

  update public.contracts
  set signed_at = now(),
      signed_name = p_signed_name,
      signed_by = v_uid,
      signed_content_hash = p_signed_content_hash,
      signed_signature_document_id = p_signature_document_id
  where id = p_contract_id;
end;
$$;

grant execute on function public.sign_own_contract(uuid, text, text, uuid) to authenticated;

create function public.countersign_contract(
  p_contract_id uuid,
  p_signed_name text,
  p_signed_content_hash text,
  p_signature_document_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_org uuid;
  v_profile_id uuid;
  v_superseded_at timestamptz;
  v_is_deed boolean;
  v_countersigned_at timestamptz;
begin
  select organisation_id, profile_id, superseded_at, is_deed, countersigned_at
    into v_org, v_profile_id, v_superseded_at, v_is_deed, v_countersigned_at
  from public.contracts
  where id = p_contract_id
  for update;

  if v_org is null then
    raise exception 'Contract not found.';
  end if;
  -- Closes a real gap: is_admin(v_org) alone previously satisfied this check
  -- with no self-exclusion, so an Admin could countersign their own
  -- contract. Mirrors migration 0045's fix for SOP self-countersigning.
  if v_profile_id = v_uid then
    raise exception 'You cannot countersign your own contract.';
  end if;
  if not (public.is_admin(v_org) or (public.can_verify(v_org) and public.worker_service(v_profile_id) = public.current_service())) then
    raise exception 'You are not allowed to countersign contracts.';
  end if;
  if v_superseded_at is not null then
    raise exception 'This contract has been replaced.';
  end if;
  if v_is_deed then
    raise exception 'This contract is a deed and is signed on paper, not in the portal.';
  end if;
  if v_countersigned_at is not null then
    return;
  end if;

  update public.contracts
  set countersigned_at = now(),
      countersigned_name = p_signed_name,
      countersigned_by = v_uid,
      countersigned_content_hash = p_signed_content_hash,
      countersigned_signature_document_id = p_signature_document_id
  where id = p_contract_id;
end;
$$;

grant execute on function public.countersign_contract(uuid, text, text, uuid) to authenticated;
